services:
  profitableviewapi:
    image: profitableviewapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: ["--fake"]
    secrets:
      - jwt_key
    
secrets:
  jwt_key:
    file: ./secrets/jwt_key.txt